/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-02-13 00:41:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/hushe/dev/eclipse-jee-2018-12-R-win32-x86_64/gware/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gware/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1549773277699L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <!-- <META HTTP-EQUIV=\"refresh\" CONTENT=\"60\"> -->\r\n");
      out.write("  <title>Calendar</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap ref -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- fullcalendar ref -->\r\n");
      out.write("<link rel='stylesheet' href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fullcalendar/fullcalendar.css' />\r\n");
      out.write("\r\n");
      out.write("<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fullcalendar/lib/moment.min.js'></script>\r\n");
      out.write("<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fullcalendar/fullcalendar.js'></script>\r\n");
      out.write("<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fullcalendar/lang/ko.js'></script>\r\n");
      out.write("\r\n");
      out.write("<!-- summernote -->\r\n");
      out.write("<link href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jscolor -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/jscolor.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var roomname = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("var username = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("var chief = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chief}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("console.log(roomname);\r\n");
      out.write("console.log(username);\r\n");
      out.write("var events_array = [];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t  $('#summernote').summernote({\r\n");
      out.write("\t\t  lang: 'ko-KR',\r\n");
      out.write("\t      height: 200,\r\n");
      out.write("\t      popover: {\r\n");
      out.write("\t    \t  image:[],\r\n");
      out.write("\t    \t  link:[],\r\n");
      out.write("\t    \t  air:[]\r\n");
      out.write("\t      },\r\n");
      out.write("\t      toolbar: [\r\n");
      out.write("\t    \t    // [groupName, [list of button]]\r\n");
      out.write("\t    \t    ['style', ['bold', 'italic', 'underline', 'clear']],\r\n");
      out.write("\t    \t    ['font', ['strikethrough', 'superscript', 'subscript']],\r\n");
      out.write("\t    \t    ['fontsize', ['fontsize']],\r\n");
      out.write("\t    \t    ['color', ['color']],\r\n");
      out.write("\t    \t    ['para', ['ul', 'ol', 'paragraph']],\r\n");
      out.write("\t    \t    ['height', ['height']]\r\n");
      out.write("\t    \t  ]\r\n");
      out.write("\t  });\r\n");
      out.write("\t});\r\n");
      out.write("  \r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("    // We will refer to $calendar in future code\r\n");
      out.write("    var $calendar = $(\"#calendar\").fullCalendar({ //start of options\r\n");
      out.write("        //weekends : false, // do not show saturday/sunday\r\n");
      out.write("        header: {\r\n");
      out.write("          left: 'prevYear,nextYear',\r\n");
      out.write("          center: 'title',\r\n");
      out.write("          right: 'today,month,agendaDay,agendaWeek prev,next'\r\n");
      out.write("        },\r\n");
      out.write("        // Make possible to respond to clicks and selections\r\n");
      out.write("        selectable: true,\r\n");
      out.write("        // allow \"more\" link when too many events\r\n");
      out.write("        eventLimit: true,\r\n");
      out.write("        navLinks: true,\r\n");
      out.write("        // Make events editable, globally\r\n");
      out.write("        editable: true,\r\n");
      out.write("        \r\n");
      out.write("        //defaultView: 'listWeek',\r\n");
      out.write("        \r\n");
      out.write("      //Drop =================================\r\n");
      out.write("        eventDrop: function(event, delta, revertFunc) {\r\n");
      out.write("        \t\r\n");
      out.write("        \t\tif (event.username == username || chief == username) {\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\tif(confirm(\"정말 변경하시겠습니까?\")){\r\n");
      out.write("        \t\t\t\tvar data = {\r\n");
      out.write("                      \t\t  calnum: event.calnum,\r\n");
      out.write("                                title: event.title,\r\n");
      out.write("                                start: event.start,\r\n");
      out.write("                                end: event.end\r\n");
      out.write("                              };\r\n");
      out.write("                      console.log(data);\r\n");
      out.write("                      $.ajax({\r\n");
      out.write("                          type: 'GET',\r\n");
      out.write("                          url: \"./modifyEvent.do\",\r\n");
      out.write("                          data: {\r\n");
      out.write("                            \"event\": JSON.stringify(data),\r\n");
      out.write("                          },\r\n");
      out.write("                          success: function(data) {\r\n");
      out.write("            \t\t\t\t\tconsole.log(data);\r\n");
      out.write("                              // Call the \"updateEvent\" method\r\n");
      out.write("                              $calendar.fullCalendar(\"updateEvent\", event);\r\n");
      out.write("                              \r\n");
      out.write("                              return;\r\n");
      out.write("                          }\r\n");
      out.write("                        });\r\n");
      out.write("        \t\t\t}else{\r\n");
      out.write("            \t\t      revertFunc();\r\n");
      out.write("            \t\t\t  return;   \r\n");
      out.write("                      }\r\n");
      out.write("                      \r\n");
      out.write("                    \r\n");
      out.write("        \t    }else{\r\n");
      out.write("        \t    \t\r\n");
      out.write("        \t\t\t  alert(\"본인의 이벤트만 변경할 수 있습니다.\")\r\n");
      out.write("        \t\t      revertFunc();\r\n");
      out.write("        \t\t\t  return;        \t    \t\r\n");
      out.write("        \t    \t\r\n");
      out.write("        \t    }\r\n");
      out.write("        },\r\n");
      out.write("        \r\n");
      out.write("        eventResize: function(event, delta, revertFunc) {\r\n");
      out.write("        \t\r\n");
      out.write("        \r\n");
      out.write("    \t\tif (event.username == username || chief == username) {\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\tif(confirm(\"정말 변경하시겠습니까?\")){\r\n");
      out.write("    \t\t\t\tvar data = {\r\n");
      out.write("                  \t\t  calnum: event.calnum,\r\n");
      out.write("                            title: event.title,\r\n");
      out.write("                            start: event.start,\r\n");
      out.write("                            end: event.end\r\n");
      out.write("                          };\r\n");
      out.write("                  console.log(data);\r\n");
      out.write("                  $.ajax({\r\n");
      out.write("                      type: 'GET',\r\n");
      out.write("                      url: \"./modifyEvent.do\",\r\n");
      out.write("                      data: {\r\n");
      out.write("                        \"event\": JSON.stringify(data),\r\n");
      out.write("                      },\r\n");
      out.write("                      success: function(data) {\r\n");
      out.write("        \t\t\t\t\tconsole.log(data);\r\n");
      out.write("                          // Call the \"updateEvent\" method\r\n");
      out.write("                          $calendar.fullCalendar(\"updateEvent\", event);\r\n");
      out.write("                          \r\n");
      out.write("                          return;\r\n");
      out.write("                      }\r\n");
      out.write("                    });\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("        \t\t      revertFunc();\r\n");
      out.write("        \t\t\t  return;   \r\n");
      out.write("                  }\r\n");
      out.write("                  \r\n");
      out.write("                \r\n");
      out.write("    \t    }else{\r\n");
      out.write("    \t    \t\r\n");
      out.write("    \t\t\t  alert(\"본인의 이벤트만 변경할 수 있습니다.\")\r\n");
      out.write("    \t\t      revertFunc();\r\n");
      out.write("    \t\t\t  return;        \t    \t\r\n");
      out.write("    \t    \t\r\n");
      out.write("    \t    }\r\n");
      out.write("        },\r\n");
      out.write("        //This is the callback that will be triggered when a selection is made\r\n");
      out.write("        /*select: function(start, end, jsEvent, view) {\r\n");
      out.write("          alert(start.format(\"MM/DD/YYYY hh:mm a\") + \" to \" + end.format(\"MM/DD/YYYY h\\\r\n");
      out.write("          h:mm a\") + \" in view \" + view.name);\r\n");
      out.write("        },*/\r\n");
      out.write("        eventRender: function(event, element, view) {\r\n");
      out.write("              \tif (view.name == 'listDay') {\r\n");
      out.write("              \t\telement.find(\".fc-list-item-time\").append(\"<span class='closeon'>X</span>\");\r\n");
      out.write("              \t} else {\r\n");
      out.write("              \t\telement.find(\".fc-content\").prepend(\"<span class='closeon'>X</span>\");\r\n");
      out.write("              \t}\r\n");
      out.write("             \t\telement.find(\".closeon\").on('click', function(e) {\r\n");
      out.write("             \t\t\t\r\n");
      out.write("             \t\t\t\r\n");
      out.write("                \t\tif (event.username == username || chief == username) {\r\n");
      out.write("                \t\t\t\r\n");
      out.write("                \t\t\tif(confirm(\"정말 삭제하시겠습니까?\")){\r\n");
      out.write("                \t\t\t\t\r\n");
      out.write("                \t\t\t\tvar data = {\r\n");
      out.write("                                \t\tcalnum: event.calnum,\r\n");
      out.write("                                        title: event.title,\r\n");
      out.write("                                        start: event.start,\r\n");
      out.write("                                        end: event.end\r\n");
      out.write("                                      };\r\n");
      out.write("                                \r\n");
      out.write("                                $.ajax({\r\n");
      out.write("                                    type: 'POST',\r\n");
      out.write("                                    url: \"./removeEvent.do\",\r\n");
      out.write("                                    data: {\r\n");
      out.write("                                      \"event\": JSON.stringify(data),\r\n");
      out.write("                                    },\r\n");
      out.write("                                    success: function(data) {\r\n");
      out.write("                                  \t  console.log(data);\r\n");
      out.write("                                  \t$('#calendar').fullCalendar('removeEvents',event._id);\r\n");
      out.write("                                    }\r\n");
      out.write("                                  });\r\n");
      out.write("                              \te.stopPropagation();\r\n");
      out.write("                              \treturn;\r\n");
      out.write("                              \r\n");
      out.write("                \t\t\t}else{\r\n");
      out.write("                \t\t\t\te.stopPropagation();\r\n");
      out.write("                      \t\t  \treturn;   \r\n");
      out.write("                              }\r\n");
      out.write("                              \r\n");
      out.write("                            \r\n");
      out.write("                \t    }else{\r\n");
      out.write("                \t    \t\r\n");
      out.write("                \t    \te.stopPropagation();\r\n");
      out.write("                  \t\t  \talert(\"본인의 이벤트만 삭제하실 수 있습니다.\")\r\n");
      out.write("                  \t\t  \treturn;        \t    \t\r\n");
      out.write("                \t    \t\r\n");
      out.write("                \t    }\t\t\r\n");
      out.write("             \t\t\t\r\n");
      out.write("             \t\t\t\r\n");
      out.write("              \t\t});\r\n");
      out.write("              },\r\n");
      out.write("        select: function(start, end, jsEvent, view) {\r\n");
      out.write("          // Ask for a title. If empty it will default to \"New event\"\r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("          $('#start_date').val(moment(start).format('YYYY-MM-DD'));\r\n");
      out.write("          $('#start_time').val(moment(start).format('hh:mm:ss'));\r\n");
      out.write("          $('#end_date').val(moment(end).format('YYYY-MM-DD'));\r\n");
      out.write("          $('#end_time').val(moment(end).format('hh:mm:ss'));\r\n");
      out.write("          \r\n");
      out.write("          $(\"#myModal\").modal();\r\n");
      out.write(" \r\n");
      out.write("        }, // End select callback\r\n");
      out.write("        // Callback triggered when we click on an event\r\n");
      out.write("        eventClick: function(event, jsEvent, view) {\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("    \t\tif (event.username == username || chief == username) {\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t// Ask for a title. If empty it will default to \"New event\"\r\n");
      out.write("    \t          var newTitle = prompt(\"변경할 제목을 입력해 주세요\", event.title);\r\n");
      out.write("    \t          // If did not pressed Cancel button\r\n");
      out.write("    \t          if (newTitle != null) {\r\n");
      out.write("    \t            // Update event\r\n");
      out.write("    \t            event.title = newTitle.trim() != \"\" ? newTitle : event.title;\r\n");
      out.write("    \t            \r\n");
      out.write("    \t              var data = {\r\n");
      out.write("    \t            \t\t  calnum: event.calnum,\r\n");
      out.write("    \t                      title: event.title,\r\n");
      out.write("    \t                      start: event.start,\r\n");
      out.write("    \t                      end: event.end\r\n");
      out.write("    \t                    };\r\n");
      out.write("    \t            \r\n");
      out.write("    \t            $.ajax({\r\n");
      out.write("    \t                type: 'GET',\r\n");
      out.write("    \t                url: \"./modifyEvent.do\",\r\n");
      out.write("    \t                data: {\r\n");
      out.write("    \t                  \"event\": JSON.stringify(data),\r\n");
      out.write("    \t                },\r\n");
      out.write("    \t                success: function(data) {\r\n");
      out.write("    \t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("    \t                    // Call the \"updateEvent\" method\r\n");
      out.write("    \t                    $calendar.fullCalendar(\"updateEvent\", event);\r\n");
      out.write("    \t                }\r\n");
      out.write("    \t              });\r\n");
      out.write("    \t          }else{\r\n");
      out.write("        \t\t      revertFunc();\r\n");
      out.write("        \t\t\t  return;    \r\n");
      out.write("    \t          }\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t    }else{\r\n");
      out.write("    \t\t\t  alert(\"본인의 이벤트만 변경할 수 있습니다.\");\r\n");
      out.write("    \t\t      revertFunc();\r\n");
      out.write("    \t\t\t  return;    \r\n");
      out.write("    \t    }\r\n");
      out.write("    \t\r\n");
      out.write("        \t\r\n");
      out.write("        }, // End callback eventClick\r\n");
      out.write("        events: events_array\r\n");
      out.write("      } //End of options\r\n");
      out.write("    );\r\n");
      out.write("  });//$ready\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  function registBtn(){\r\n");
      out.write("\t  \r\n");
      out.write("\t  var stitle = $('#sname').val();\r\n");
      out.write("\t  var scontent = $('#summernote').val();\r\n");
      out.write("\t  \r\n");
      out.write("\t  var start = $('#start_date').val();\r\n");
      out.write("\t  var end = $('#end_date').val();\r\n");
      out.write("\t  \r\n");
      out.write("\t  var start_time = $('#start_time').val();\r\n");
      out.write("\t  var end_time = $('#end_time').val();\r\n");
      out.write("\t   \r\n");
      out.write("\t  \r\n");
      out.write("\t  /* console.log(stitle);\r\n");
      out.write("\t  console.log(scontent);\r\n");
      out.write("\t  console.log(start);\r\n");
      out.write("\t  console.log(end);\r\n");
      out.write("\t  console.log(start_time)\r\n");
      out.write("\t  console.log(end_time) */\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  if(stitle.trim() == ''){\r\n");
      out.write("\t\t  alert('제목을 다시 입력해 주세요');\r\n");
      out.write("\t\t  $('#sname').val('');\r\n");
      out.write("\t\t  return;\r\n");
      out.write("\t  }\r\n");
      out.write("      \r\n");
      out.write("\t  \r\n");
      out.write("      if (stitle != '' && scontent != '' && start != null && end != null) {\r\n");
      out.write("      \tvar st = start+\" \"+start_time;\r\n");
      out.write("      \tvar en = end+\" \"+end_time;\r\n");
      out.write("      \t\r\n");
      out.write("      \tconsole.log(st)\r\n");
      out.write("      \tconsole.log(en)\r\n");
      out.write("      \t\r\n");
      out.write("\t\tif(st > en){\r\n");
      out.write("\t\t\talert(\"종료 일이 시작일 보다 빠를 수 없습니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  \r\n");
      out.write("        // Create event\r\n");
      out.write("        /* var data = {\r\n");
      out.write("          'title': stitle.trim(),\r\n");
      out.write("          'content': scontent,\r\n");
      out.write("          'start': st,\r\n");
      out.write("          'end': en,\r\n");
      out.write("          'member_id': '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("        }; */\r\n");
      out.write("        var param = \"\";\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          type: 'POST',\r\n");
      out.write("          url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/calendar/addEvent\",\r\n");
      out.write("          data: {\r\n");
      out.write("            \"event\": JSON.stringify(data),\r\n");
      out.write("          },\r\n");
      out.write("          success: function(data) {\r\n");
      out.write("        \t  if(data == 1){\r\n");
      out.write("        \t\t  \r\n");
      out.write("        \t  \r\n");
      out.write("              var event = {\r\n");
      out.write("                      'title': stitle.trim(),\r\n");
      out.write("                      'content': scontent,\r\n");
      out.write("                      'start': st,\r\n");
      out.write("                      'end': en,\r\n");
      out.write("                      'color': 'red'\r\n");
      out.write("                    };\r\n");
      out.write("              console.log(event);\r\n");
      out.write("              \r\n");
      out.write("            $calendar.fullCalendar(\"renderEvent\", event, true);\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            $(\"#myModal\").modal('hide');\r\n");
      out.write("            $('#sname').val('');\r\n");
      out.write("            $('#summernote').val('');\r\n");
      out.write("        \t  }else{\r\n");
      out.write("        \t\t  alert('일정 등록 오류가 발생하였습니다.')\r\n");
      out.write("        \t\t  return;\r\n");
      out.write("        \t  }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("        // Push event into fullCalendar's array of events\r\n");
      out.write("        // and displays it. The last argument is the\r\n");
      out.write("        // \"stick\" value. If set to true the event\r\n");
      out.write("        // will \"stick\" even after you move to other\r\n");
      out.write("        // year, month, day or week.\r\n");
      out.write("      }else{\r\n");
      out.write("    \t  alert('일정을 입력해주세요');\r\n");
      out.write("    \t  return;\r\n");
      out.write("      };\r\n");
      out.write("      // Whatever happens, unselect selection\r\n");
      out.write("      //$calendar.fullCalendar(\"unselect\");\r\n");
      out.write("\t  \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style media=\"screen\">\r\n");
      out.write("  #calendar {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("  }\r\n");
      out.write("  .centered {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t왼쪽 메뉴바\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div>캘린더 설정</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- The calendar container -->\r\n");
      out.write("\t\t\t<div class=\"col-9\">\r\n");
      out.write("\t\t\t<div align= \"center\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-toggle=\"modal\" data-target=\"#myModal\">일정 등록하기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"calendar\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"dayModal\" role=\"dialog\">\r\n");
      out.write("    \t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"form-horizontal\" role=\"form\" id=\"sform\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schedule/sadd.kitri\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- MODAL HEADER -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">일정 보기</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- MODAL BODY -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\" id=\"modalBody\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- hidden value -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"pid\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div align= \"center\"><label class=\"col-lg-2\">구분</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- spring form 태그로 select 불러오기 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-10\" id=\"pselect\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div align= \"center\"><label class=\"col-lg-2\">시작날짜</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-10\" id=\"pstart\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div align= \"center\"><label class=\"col-lg-2\">종료날짜</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-10\" id=\"pend\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div align= \"center\"><label class=\"col-lg-2\">제목</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-10\" id=\"psubject\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div align= \"center\"><label class=\"col-lg-2\">내용</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"pcontent\" class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" id=\"modifyBtn\">수정하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" id=\"deleteBtn\">삭제하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input class=\"jscolor\" value=\"ab2567\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 스케쥴 등록 MODAL 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"form-horizontal\" role=\"form\" id=\"sform\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schedule/sadd.kitri\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- MODAL HEADER -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">일정 등록하기</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close float-right\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- MODAL BODY -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\" control-label \" style=\"padding-left: 40px;\">구분</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- spring form 태그로 select 불러오기 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\" control-label \" style=\"padding-left: 20px;\">색상</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"color2\" type=\"hidden\" id=\"color_value\" value=\"99cc00\">\r\n");
      out.write("\t       \t\t \t\t\t\t\t\t\t\t<button class=\"jscolor {valueElement: 'color_value'}\">Pick a color</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"jscolor\" value=\"ab2567\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\" control-label \" style=\"padding-left: 40px;\">시작날짜</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"date\" name=\"sstart_date\" id=\"start_date\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"time\" name=\"sstart_time\" id=\"start_time\" class=\"st\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\" control-label \" style=\"padding-left: 40px;\">종료날짜</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"date\" name=\"send_date\" id=\"end_date\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"time\" name=\"send_time\" id=\"end_time\" class=\"st\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\" control-label \" style=\"padding-left: 40px;\">제목</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sname\" id=\"sname\" style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea id=\"summernote\" name=\"summernote\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id=\"registBtn\" onclick=\"registBtn();\">등록하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
